### CADASTRO

POST http://localhost:3003/user/signup
Content-Type: application/json

{
	"name": "teste3",
	"email": "teste3@lbn.com",
	"password": "123456",
    "role":"ADMIN"
}

### LOGIN

POST http://localhost:3003/user/login
Content-Type: application/json

{
	"email": "teste2@lbn.com",
	"password": "123456"
}

// pegar usuarios
GET http://localhost:3003/user/users


// pegar usuarios pelo id
###
GET http://localhost:3003/user/users/:id

//criar bandas
###
POST http://localhost:3003/band/bands
Content-Type: application/json

{
"name": "The Beatles",
"music_genre": " rock", 
"responsible": "John Lennon"  
}
  
//pegar banda pelo id
###
GET http://localhost:3003/band/bands/:id